import NextAuthProvider from "@/components/client/NextAuthProvider";
import "./globals.css";
import SignIn from "@/components/client/SignIn";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
      <NextAuthProvider>
      <div className="navbar bg-base-100">
          <div className="flex-1">
            <a className="btn btn-ghost text-xl">App</a>
          </div>
          <div className="flex-none">
            <ul className="menu menu-horizontal px-1">
              <li><a href="/reminders">Reminder</a></li>
            </ul>
          </div>
          <SignIn/>
        </div>
        {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}